{
 "title": "MAINDASHBOARD",
 "description": "MAINDASHBOARD",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: -1m, stop: now())  // 최근 1분 데이터를 조회\r\n  |> filter(fn: (r) => contains(value: r[\"_measurement\"], set: [\"machine_status\", \"machine_data\", \"machine_data1\", \"machine_data2\", \"machine_data3\", \"machine_data4\", \"machine_data5\", \"machine_data6\", \"machine_data7\", \"machine_data8\", \"machine_data9\", \"machine_data10\", \"machine_data11\"]))\r\n  |> map(fn: (r) => ({ r with _measurement: \"machine_status\" }))  // 모든 measurement를 \"machine_status\"로 묶음\r\n  |> drop(columns: [\"_field\", \"device_name\", \"status\"])  // 필드 관련 정보 제거\r\n  |> aggregateWindow(every: 1s, fn: count, createEmpty: false)  // 1초 단위 메시지 수 계산\r\n  |> group(columns: [\"_time\"])  // 시간별 그룹화\r\n  |> sort(columns: [\"_time\"], desc: false)  // 시간 순으로 정렬\r\n  |> yield(name: \"total_count_per_second\")\r\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: -60m, stop: now())  // 최근 5분 데이터를 조회\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\r\n  |> aggregateWindow(every: 1s, fn: count, createEmpty: false)  // 1초 단위 메시지 수 계산\r\n  |> sort(columns: [\"_value\"], desc: true)  // 데이터 수가 많은 순으로 정렬\r\n  |> yield(name: \"sorted_count\")"
    }
   ]
  },
  { "title": "System_Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU_Usage(%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "queryExecutor",
     "query": "from(bucket: \"system_metrics\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"cpu\" and r._field == \"usage_idle\" and r.cpu == \"cpu-total\")\r\n  |> map(fn: (r) => ({ r with host: \"CPU\" }))\r\n  |> map(fn: (r) => ({ r with _value: 100.0 - r._value }))\r\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])\r\n",
     "select": [
      [
       { "params": [ "queriesActive" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "stats-node-0.infra.ramcloud.io" }
     ]
    }
   ]
  },
  {
   "title": "Memory_Used(%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "queryExecutor",
     "query": "from(bucket: \"system_metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"used_percent\")\r\n  |> map(fn: (r) => ({ r with host: \"Memory\" }))\r\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])\r\n  |> aggregateWindow(every: 5s, fn: mean, createEmpty: false) \r\n",
     "select": [
      [
       { "params": [ "queriesActive" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "stats-node-0.infra.ramcloud.io" }
     ]
    }
   ]
  },
  {
   "title": "Memory_Useable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "queryExecutor",
     "query": "from(bucket: \"system_metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"available\")\r\n  |> map(fn: (r) => ({ r with host: \"Memory\" }))\r\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])\r\n  |> aggregateWindow(every: 5s, fn: mean, createEmpty: false) \r\n",
     "select": [
      [
       { "params": [ "queriesActive" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "stats-node-0.infra.ramcloud.io" }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "used_percent = from(bucket: \"system_metrics\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"disk\" and r._field == \"used_percent\")\r\n  |> map(fn: (r) => ({ r with display_name: r.path }))\r\n  |> rename(columns: { _value: \"Disk Usage (%)\" })  // \"used_percent\"를 \"Disk Usage (%)\"로 변경\r\n\r\ntotal_capacity = from(bucket: \"system_metrics\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"disk\" and r._field == \"total\")\r\n  |> map(fn: (r) => ({ r with display_name: r.path, _value: float(v: r._value) / (1024.0 * 1024.0 * 1024.0) }))\r\n  |> rename(columns: { _value: \"Total Disk Capacity (GB)\" })  // \"total_capacity\"를 \"Total Disk Capacity (GB)\"로 변경\r\n\r\njoin(\r\n    tables: {used_percent: used_percent, total_capacity: total_capacity},\r\n    on: [\"_time\", \"display_name\"]\r\n  )\r\n  |> keep(columns: [\"_time\", \"display_name\", \"Disk Usage (%)\", \"Total Disk Capacity (GB)\"])  // 변경된 필드 이름 유지\r\n"
    }
   ]
  },
  {
   "title": "RabbitMQ Message Count",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queryExecutor",
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\" or r[\"_field\"] == \"temperature\")\r\n  |> drop(columns: [\"_start\", \"_stop\"])  // 시간 태그 제거\r\n  |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: false)  // 메시지 수 계산\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> yield(name: \"count\")\r\n",
     "select": [
      [
       { "params": [ "queryDurationNs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Data_Feeder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"FEEDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"speed_sv\" or r[\"_field\"] == \"speed_pv\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tension",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"FEEDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tension_pv\" or r[\"_field\"] == \"tension_sv\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"FEEDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"volt\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current(A)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"FEEDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Power(W)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"FEEDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"FEEDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dancer_Pos",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"FEEDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"dancer_pos\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"FEEDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rpm\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Torque",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"FEEDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"torque\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Hz",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"FEEDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Hz\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Data_Unwinder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"UNWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"speed_sv\" or r[\"_field\"] == \"speed_pv\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tension",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"UNWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tension_pv\" or r[\"_field\"] == \"tension_sv\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"UNWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"volt\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current(A)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"UNWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Power(W)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"UNWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"UNWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dancer_Pos",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"UNWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"dancer_pos\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"UNWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rpm\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Torque",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"UNWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"torque\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Hz",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"UNWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Hz\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Data_Rewinder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"REWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"speed_sv\" or r[\"_field\"] == \"speed_pv\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tension",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"REWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tension_pv\" or r[\"_field\"] == \"tension_sv\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"REWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"volt\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current(A)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"REWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Power(W)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"REWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"REWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dancer_Pos",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 47 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"REWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"dancer_pos\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"REWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rpm\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Torque",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"REWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"torque\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Hz",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machine_status\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"REWINDER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Hz\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Mariadb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Data_input (최신10개)",
   "type": "table",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data_Input_InfluxDB",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 15, "x": 9, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {}
   ]
  }
 ]
}