version: "3.8"

services:
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file: ./credentials.env
    volumes:
      - /data/mariadb_db-mariadb/_data/influxdb:/var/lib/influxdb2
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ~/projects/Rabbitmq-Grafana/ssl/bigdatalab.cloud249.com:/etc/ssl
      - ./scripts/installsetup.sh:/usr/local/bin/install_and_setup.sh  # 설치 및 설정 스크립트 복사
      - ./scripts/backup_influxdb.sh:/usr/local/bin/influxdb_backup.sh               # 백업 스크립트 복사
    command: |
      sh -c "
      chmod +x /usr/local/bin/install_and_setup.sh &&
      /usr/local/bin/install_and_setup.sh
      "
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "curl", "-k", "--fail", "https://localhost:8086/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  telegraf:
    image: telegraf
    container_name: telegraf
    ports:
      - "8092:8092"
      - "8094:8094"
      - "8125:8125"
    env_file: ./credentials.env
    volumes:
      - ./telegraf-consumer.conf:/etc/telegraf/telegraf.conf
    networks:
      - monitoring
    depends_on:
      influxdb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883
    env_file: ./credentials.env
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/plugins:/etc/rabbitmq/enabled_plugins
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    env_file: ./credentials.env
    ports:
      - '3000:3000'  # Expose Grafana on port 3000
    volumes:
      - grafana_data:/var/lib/grafana  # Mount the Grafana data directory
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ~/projects/Rabbitmq-Grafana/ssl/bigdatalab.cloud249.com:/etc/ssl
    networks:
      - monitoring
    depends_on:
      influxdb:
        condition: service_healthy

volumes:
  grafana_data: {}  # Volume for Grafana data
  influxdb_data: {}  # Volume for InfluxDB data
  rabbitmq_data: {}

networks:
  monitoring:
    external: true  # Use an external network named 'monitoring'
